// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Profile struct {
	ID       int64
	Location string
	Note     string
}

type Quest struct {
	ID             string
	Title          string
	Description    string
	DurationBucket string
	Source         string
	Status         string
	Tags           string
	PhotoPath      sql.NullString
	XpAwarded      sql.NullInt64
	CreatedAt      string
	CompletedAt    sql.NullString
}
