// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	AcceptQuest(ctx context.Context, id string) (Quest, error)
	CompleteQuest(ctx context.Context, arg CompleteQuestParams) (Quest, error)
	CountCompleted(ctx context.Context) (int64, error)
	CountQuests(ctx context.Context) (int64, error)
	CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error)
	DeleteQuest(ctx context.Context, id string) error
	GetProfile(ctx context.Context) (Profile, error)
	GetQuest(ctx context.Context, id string) (Quest, error)
	ListQuests(ctx context.Context) ([]Quest, error)
	ListQuestsByStatus(ctx context.Context, status string) ([]Quest, error)
	TotalCompletedXp(ctx context.Context) (int64, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
}

var _ Querier = (*Queries)(nil)
