// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quests.sql

package store

import (
	"context"
	"database/sql"
)

const acceptQuest = `-- name: AcceptQuest :one
UPDATE quests SET status = 'active' WHERE id = ? AND status = 'generated'
RETURNING id, title, description, duration_bucket, source, status, tags, photo_path, xp_awarded, created_at, completed_at
`

func (q *Queries) AcceptQuest(ctx context.Context, id string) (Quest, error) {
	row := q.db.QueryRowContext(ctx, acceptQuest, id)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationBucket,
		&i.Source,
		&i.Status,
		&i.Tags,
		&i.PhotoPath,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeQuest = `-- name: CompleteQuest :one
UPDATE quests
SET status = 'completed', completed_at = ?, photo_path = ?, xp_awarded = ?
WHERE id = ? AND status = 'active'
RETURNING id, title, description, duration_bucket, source, status, tags, photo_path, xp_awarded, created_at, completed_at
`

type CompleteQuestParams struct {
	CompletedAt sql.NullString
	PhotoPath   sql.NullString
	XpAwarded   sql.NullInt64
	ID          string
}

func (q *Queries) CompleteQuest(ctx context.Context, arg CompleteQuestParams) (Quest, error) {
	row := q.db.QueryRowContext(ctx, completeQuest,
		arg.CompletedAt,
		arg.PhotoPath,
		arg.XpAwarded,
		arg.ID,
	)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationBucket,
		&i.Source,
		&i.Status,
		&i.Tags,
		&i.PhotoPath,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countCompleted = `-- name: CountCompleted :one
SELECT COUNT(*) AS count FROM quests WHERE status = 'completed'
`

func (q *Queries) CountCompleted(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompleted)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuests = `-- name: CountQuests :one
SELECT COUNT(*) AS count FROM quests
`

func (q *Queries) CountQuests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuest = `-- name: CreateQuest :one
INSERT INTO quests (id, title, description, duration_bucket, source, status, tags, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, description, duration_bucket, source, status, tags, photo_path, xp_awarded, created_at, completed_at
`

type CreateQuestParams struct {
	ID             string
	Title          string
	Description    string
	DurationBucket string
	Source         string
	Status         string
	Tags           string
	CreatedAt      string
}

func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error) {
	row := q.db.QueryRowContext(ctx, createQuest,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DurationBucket,
		arg.Source,
		arg.Status,
		arg.Tags,
		arg.CreatedAt,
	)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationBucket,
		&i.Source,
		&i.Status,
		&i.Tags,
		&i.PhotoPath,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteQuest = `-- name: DeleteQuest :exec
DELETE FROM quests WHERE id = ?
`

func (q *Queries) DeleteQuest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteQuest, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, location, note FROM profile WHERE id = 1
`

func (q *Queries) GetProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile)
	var i Profile
	err := row.Scan(&i.ID, &i.Location, &i.Note)
	return i, err
}

const getQuest = `-- name: GetQuest :one
SELECT id, title, description, duration_bucket, source, status, tags, photo_path, xp_awarded, created_at, completed_at FROM quests WHERE id = ?
`

func (q *Queries) GetQuest(ctx context.Context, id string) (Quest, error) {
	row := q.db.QueryRowContext(ctx, getQuest, id)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationBucket,
		&i.Source,
		&i.Status,
		&i.Tags,
		&i.PhotoPath,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listQuests = `-- name: ListQuests :many
SELECT id, title, description, duration_bucket, source, status, tags, photo_path, xp_awarded, created_at, completed_at FROM quests ORDER BY created_at DESC
`

func (q *Queries) ListQuests(ctx context.Context) ([]Quest, error) {
	rows, err := q.db.QueryContext(ctx, listQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quest{}
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DurationBucket,
			&i.Source,
			&i.Status,
			&i.Tags,
			&i.PhotoPath,
			&i.XpAwarded,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestsByStatus = `-- name: ListQuestsByStatus :many
SELECT id, title, description, duration_bucket, source, status, tags, photo_path, xp_awarded, created_at, completed_at FROM quests WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListQuestsByStatus(ctx context.Context, status string) ([]Quest, error) {
	rows, err := q.db.QueryContext(ctx, listQuestsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quest{}
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DurationBucket,
			&i.Source,
			&i.Status,
			&i.Tags,
			&i.PhotoPath,
			&i.XpAwarded,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalCompletedXp = `-- name: TotalCompletedXp :one
SELECT CAST(COALESCE(SUM(xp_awarded), 0) AS INTEGER) AS total FROM quests WHERE status = 'completed'
`

func (q *Queries) TotalCompletedXp(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalCompletedXp)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profile SET location = ?, note = ? WHERE id = 1
RETURNING id, location, note
`

type UpdateProfileParams struct {
	Location string
	Note     string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile, arg.Location, arg.Note)
	var i Profile
	err := row.Scan(&i.ID, &i.Location, &i.Note)
	return i, err
}
